import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gino Missael - Desarrollador</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.main}>
          <h1 className={`${styles.title} animate__animated animate__fadeInUp`}>
            Gino Missael
          </h1>

          <div className={styles.wrapper}>
            <div className={styles["typing-demo"]}>Fullstack Developer</div>
          </div>
        </div>
        <div>
          <p>
            Hola soy gino missael un desarrollador con mas de 6 años de
            experiencia
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img src="/img/mx-flag.png" width="25px" height="25px" />
          Mexican talent
        </a>
      </footer>
    </div>
  );
}
